project:
  type: website

website:
  title: "Dr. Elizabeth Delmelle - MUSA 5080 Portfolio"
  description: "Sample portfolio for Public Policy Analytics class"
  navbar:
    title: "Portfolio"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
      - text: "Labs"
        menu:
           - href: labs/
             text: "All Labs"
           - href: labs/sample-census-analysis.qmd
             text: "Sample Census Analysis"
    right:
      - icon: github
        href: https://github.com/ECDelmelle/MUSA-5080-instructor-portfolio

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show code"

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
